version: '3.8'

services:
  db:
    build:
      context: server
      dockerfile: Postgres.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
